columns:
  - total
  - seat
  - gift_certificate
  - ('AAQ-DME', 'auto_checkin')
  - ('DME-GDZ', 'auto_checkin')
  - ('DME-ORY', 'seat')

scenarios:
  - anom_coeff: 0.833
    num_anomalies: 1
    in_a_row: False
  - anom_coeff: 0.66
    num_anomalies: 1
    in_a_row: False
  - anom_coeff: 0
    num_anomalies: 1
    in_a_row: False
  - anom_coeff: 0
    num_anomalies: 3
    in_a_row: True

time_series_params:
  1:
    - model: ProphetGamma
      interval_width: 0.92
    - model: ProphetNB
      interval_width: 0.9
    - model: ProphetNB
      interval_width: 0.97
    - model: ProphetNB
      interval_width: 0.97
  2:
    - model: ProphetNB
      interval_width: 0.93
    - model: ProphetNB
      interval_width: 0.96
    - model: ProphetNB
      interval_width: 0.98
    - model: ProphetNB
      interval_width: 0.97
  3:
    - model: ProphetNB
      interval_width: 0.96
    - model: ProphetNB
      interval_width: 0.96
    - model: ProphetNB
      interval_width: 0.95
    - model: ProphetNB
      interval_width: 0.93
